---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anki-convo-chain-deployment
  namespace: anki-convo-chain
  labels:
    app: anki-convo-chain
spec:
  replicas: 3
  selector:
    matchLabels:
      app: anki-convo-chain
  template:
    metadata:
      labels:
        app: anki-convo-chain
    spec:
      containers:
      - name: anki-convo-chain
        image: mathijsvdv/anki-convo-chain
        ports:
        - containerPort: 8800
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: anki-convo-chain-secret
              key: OPENAI_API_KEY
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: ExtraTag
      #           operator: In
      #           values:
      #           - hello-eks-managed-node-group
      # tolerations:
      # - key: team
      #   operator: Equal
      #   value: dev
      #   effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: anki-convo-chain-service
  namespace: anki-convo-chain
spec:
  ports:
  - port: 8800
    protocol: TCP
  type: ClusterIP
  selector:
    app: anki-convo-chain
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anki-convo-chain-ingress
  namespace: anki-convo-chain
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    # Should be parametrized in the future depending on the environment and team
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test

spec:
  ingressClassName: alb
  rules:
    - host: ankiconvo.mvdvlies.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: anki-convo-chain-service
                port:
                  number: 8800
