apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama
  namespace: phrasify
  labels:
    app: ollama

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
