---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anki-convo-deployment
  namespace: anki-convo
  labels:
    app: anki-convo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: anki-convo
  template:
    metadata:
      labels:
        app: anki-convo
    spec:
      containers:
      - name: anki-convo
        image: mathijsvdv/anki-convo
        ports:
        - containerPort: 8800
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: anki-convo-secret
              key: OPENAI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: anki-convo-service
  namespace: anki-convo
spec:
  selector:
    app: anki-convo
  ports:
  - protocol: TCP
    port: 8800
    targetPort: 8800
    nodePort: 30800
  type: LoadBalancer
