# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  hatch_version: "1.9.3"

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - uses: davidB/rust-cargo-make@v1
    - name: Check cargo-make version
      run: cargo make --version
    - name: Check makers version
      run: makers --version
    - uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Disable INIT_PHRASIFY_ADDON
      run: echo "INIT_PHRASIFY_ADDON=false" >> "$GITHUB_ENV"
    - name: Install dependencies
      run: uv pip install --system -r requirements/test.py${{ matrix.python-version }}.txt 'phrasify @ .'
    - name: Test package
      run: make _test_cov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
